#SELECT * FROM moviesdb.movie_actor;
#SELECT title, industry FROM moviesdb.movies;
use moviesdb;
#SELECT * FROM movies;
#SELECT title, industry FROM movies;
#SELECT * FROM movies WHERE industry='Bollywood';
#SELECT COUNT(*) FROM movies WHERE industry='Bollywood';
#SELECT distinct industry FROM movies;
#SELECT * FROM movies WHERE title LIKE '%THOR%';
#SELECT * FROM movies WHERE studio="";
#SELECT title, release_year FROM movies WHERE studio="Marvel Studios";
#SELECT * FROM movies WHERE title LIKE '%Avenger%';
#SELECT release_year FROM movies WHERE title="The Godfather";
SELECT distinct studio FROM movies  WHERE industry="Bollywood";